//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLU_ID_Generator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JED-PC\\GLUINVENTORY;Initial Catalog=dbDR;Integrated Security=True")]
        public string dbDRConnectionString {
            get {
                return ((string)(this["dbDRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DBEmployee.md" +
            "f;Integrated Security=True")]
        public string DBEmployeeConnectionString {
            get {
                return ((string)(this["DBEmployeeConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MyFile\\DTRVIEW.PDF")]
        public string path {
            get {
                return ((string)(this["path"]));
            }
            set {
                this["path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MyFile\\DTRVIEW.PDF")]
        public string biopath {
            get {
                return ((string)(this["biopath"]));
            }
            set {
                this["biopath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("markjed92@gmail.com")]
        public string esender {
            get {
                return ((string)(this["esender"]));
            }
            set {
                this["esender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jlcjed1998")]
        public string esenderpass {
            get {
                return ((string)(this["esenderpass"]));
            }
            set {
                this["esenderpass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string smtpserver {
            get {
                return ((string)(this["smtpserver"]));
            }
            set {
                this["smtpserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string portnumber {
            get {
                return ((string)(this["portnumber"]));
            }
            set {
                this["portnumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<strong><font face=""Tahoma"" size=""2px"" color=""#898988"">Jed R. Zerna</font></strong><br><br><strong><font face=""Sans Serif"" size=""2px"" font-weight=""Bold"" color=""#016601"">G. Uymatiao Jr. Construction</font></strong><br><font face=""Tahoma"" size=""1px"" color=""#898988"">49 Sta. Catalina St., Dumaguete City</font><br><font face=""Tahoma"" size=""1px"" color=""#898988"">Tel. No. (035) 225-4717; (035) 422-7677</font><br><font face=""Tahoma"" size=""1px"" color=""#898988"">Telefax No. (035) 225-3333</font><br> <font face=""Tahoma"" size=""1px"" color=""#898988"">Mobile (0998) 230-9589</font>
")]
        public string signature {
            get {
                return ((string)(this["signature"]));
            }
            set {
                this["signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ssl {
            get {
                return ((bool)(this["ssl"]));
            }
            set {
                this["ssl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jed Zerna\\Desktop\\Biometric")]
        public string attachment {
            get {
                return ((string)(this["attachment"]));
            }
            set {
                this["attachment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jed Zerna\\source\\repos\\GLU ID Generator\\GLU ID Generator")]
        public string pathCon {
            get {
                return ((string)(this["pathCon"]));
            }
            set {
                this["pathCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pspath {
            get {
                return ((string)(this["pspath"]));
            }
            set {
                this["pspath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DBEmployee.md" +
            "f;Integrated Security=True")]
        public string dbcon {
            get {
                return ((string)(this["dbcon"]));
            }
            set {
                this["dbcon"] = value;
            }
        }
    }
}
